-- create tables
create table logger (
    id                             number generated by default on null as identity  
                                   constraint logger_id_pk primary key,
    name                           varchar2(4000),
    text                           varchar2(4000),
    created                        date
)
;


-- triggers
create or replace trigger logger_biu
    before insert or update 
    on logger
    for each row
begin
    if inserting then
        :new.created := sysdate;
    end if;
end logger_biu;
/

-- load data
 
-- Generated by Quick SQL Friday May 04, 2018  11:46:46
 
/*
logger
  id 
  name vc4000
  text vc4000
  created date

# settings = { language: "EN", APEX: true }
*/
