-- create tables
create table ww_data (
    ww_id                          number generated by default on null as identity  
                                   constraint ww_data_ww_id_pk primary key,
    ww_raw                         varchar2(50),
    ww_date                        date,
    ww_weight                      number,
    ww_created                     date not null,
    ww_created_by                  varchar2(255) not null,
    ww_updated                     date not null,
    ww_updated_by                  varchar2(255) not null
)
;


-- REST ENABLE tables using Oracle REST Data Services (ORDS)
begin
    ords.enable_object(p_enabled=&gt;TRUE, p_object=&gt;'ww_data');
end;
/

-- load data
 
-- Generated by Quick SQL Monday April 30, 2018  08:51:08
 
/*
ww_data /auditcols /colprefix ww_ /rest
  raw vc 30
  date
  weight number
  
# settings = { language: "EN", APEX: true }
*/
